source ~/.vim/basic.vim
source ~/.vim/plugins.vim
source ~/.vim/statusline.vim
filetype detect
if &filetype == "python" || &filetype == "vim"
	set tabstop=4
	set expandtab
	set shiftwidth=4
elseif &filetype == "html" || &filetype == "css"
	set tabstop=2
	set shiftwidth=2
	set nolinebreak
	set colorcolumn=140
	set textwidth=140
	set wrap
endif

function PrepareBeforeWrite()
	if &filetype == "python"
		%s/^	/    /e
	endif
	%s/\s\+$//e
	%s/\^datetime\^/\=strftime("%c")/e
	set fenc=utf-8
endfunction

augroup PreWriteEdits
autocmd BufWritePre * call PrepareBeforeWrite()
augroup END
syntax on
