#!/usr/bin/env bash
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 0001 0010 0011 0100
bspc config border_width 0
bspc config window_gap 0
bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config single_monocle false
bspc config paddingless_monocle	true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Zathura desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true
bspc config normal_border_color "#272e33"
bspc config focused_border_color "#7fbbb3"
bspc config active_border_color "#1a1b26"
feh --bg-scale ~/Pictures/wallpaper.jpg &
picom -b --config ~/.config/picom/config.ini &
bash ~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
